### PR TITLE
New website with merged  documentation 

### PR DESCRIPTION
**Pull request by TobiasWinchen**
This PR introduces a new documentation system to CRPropa. All examples and documentation sources are inside the crpropa source. The make doc command compiles a webpage from the contents of the doc directory and the doxygen code markup using [sphinx](
https://www.sphinx-doc.org/en/master/).

The doc directory contains all (non redundant) content of the wiki and the example notebooks.

The documentation will be build and updated online by travis, our automatic build and test system, on every successful build of the master branch. Also the crpropa.github.io site and consequently the crpropa.desy.de will be updated with the contents of the README.md file.

Consequently, the github page and desy [page are automatically in-sync. Both contain links to the new documentation. After merging this PR, we should delete the wiki and the examples repository, respectively replace all contents with a link to the new documentation.

The current version of the documentation can be viewed here:
http://crpropa.github.io/CRPropa3/

Please feel free to make further fixes to this branch.

### CODE REVIEW

**Comment by adundovi** [comment]
Thanks @TobiasWinchen, already looks good. I'll check and contribute. BTW did we agree then to redirect the DESY web page to this one after it is ready?

**Comment by rafaelab** [comment]
> Thanks @TobiasWinchen, already looks good. I'll check and contribute. BTW did we agree then to redirect the DESY web page to this one after it is ready?

@adundovi  Since there is still a lot of polishing required, we decided to let the others know what exactly we are working on to avoid conflicts. 

And I think the conclusions from our discussion is that we will redirect the DESY website to this one once it is more or less ready.

**Comment by rafaelab** [comment]
> Since you don't modify any CRPropa code besides comments (as far as I can notice) and this is totally new "functionality" which we didn't have before - you cannot break anything with it so we can go fast and repair/modify later if necessary. Going with a detailed review with such a huge commit would not be easy, nor efficient.

I agree with Andrej. It is probably easier to go for it now and then to start modifying things later.

**Comment by TobiasWinchen** [comment]
Ok, let me just make a last commit that builds the pages on the master branch and not the sphinx branch, then we can merge.

**Comment by Froehliche-Kernschmelze** [comment]
Thanks to @TobiasWinchen for taking on this project which in my eyes is a prime example of how much value is added to a project by choosing meaning over metrics.

From what I can retrieve from the changes in the files, I'd summarise this PR as:
- There is a new website comprising most info on CRPropa (duh..)
- There is a new CRPropa-internal infrastructure passing doc info to the doc web page
- In this regard, installation protocols have been amended accordingly
- The vast amount of added lines comes from existing documentation that is now written to the central place

Since there is seems to be no change in the user concept of CRPropa nor in the physics involved, we could go for this PR as-is while referring to the possibility to modify the doc contents in the future if needed. In this regard my point is:
* Should we explain at some place how one can add further details to the documentation? This supports our plans to have any content changed post-merge.

Anyways: imho substantially well-done work over here!

**Comment by TobiasWinchen** [comment]
@Froehliche-Kernschmelze There is no new documentation, I merged the wiki and exampels repositories into doc even keeping their history. Things have been slightly reformatted, that is all.

Additional information can be added to the doc directory in the repository, `make doc` will build the page in build/doc, just point your browser to build/doc/index.html (if doxygen and sphinx is installed, see .travis.yml for the versions I used). Future pull requests should also update the documentation alongside the code by adding / updating the according examples. This makes it easier to keep both in-sync.

**Comment by avvliet** [comment]
I'm okay with merging too. This probably makes it a lot easier for non-expert to find the right information on CRPropa. Thanks a lot for the work, Tobi!

One small thing. Please change 'Howto' into 'How to' in the Readme line 52.

**Pull request merged**
