### PR TITLE
Tf17field

### PR DESCRIPTION
**Pull request by tfitoussi**
Dear all,

In this pull-request, I want to provide the implementation of the Galactic and halo magnetic field presented in [Terral & Ferrière 2017](https://ui.adsabs.harvard.edu/abs/2017A%26A...600A..29T/abstract).

I implemented all 6 models of the paper: disk (Ad1, Bd1, Dd1) + halo (C0, C1).

The models can be set as follow :
```python3
disk_model = "Ad1"
halo_model = "C0"
GMF = crpropa.TF17Field(disk_model,halo_model)
```
The field at a given position can be call as usual:
```python3
B = GMF.getField(crpropa.Vector3d(0,0,0))
```

All models have been checked by Katia Ferrière. As far as I know, the implementation is correct.

I would like to point out that from the few tests I made, the models have some problems. The Faraday rotation is indeed only fittted in the halo (excluding the Galactic plan). As a consequence, the Galactic models (Ad1, Bd1, Dd1) are poorly fitted. In particular really strong amplitudes of the magnetic field (higher than few hundreds microgauss) can appear locally.

Nevertheless, since it is implemented. I think it is worthy to include it in CRPropa.

Thank you for considering the pull-request,
Cheers,

Thomas F.

### CODE REVIEW

**Comment by adundovi** [comment]
Thanks for your contribution and the pull request. We can start a review process. However, we should first clean this PR since it brings a lot of changes from other commits and in non-related files...

**Comment by adundovi** [comment]
@MRCWirtz Why did you close this PR?

**Comment by MRCWirtz** [comment]
@adundovi I am sorry, this was not my intention, I deleted the branch tf17 which I created myself earlier and thought to be obsolete now. I was not aware that @tfitoussi was using the same branch... Can you fix this? I already contacted @TobiasWinchen for help to restore the deleted branch.

**Comment by TobiasWinchen** [comment]
I don't think that the Branch can be restored. And given that it was a dirty branch from the messed up history issue it probably shouldn't. I copied the relevant parts to a new branch in [my fork](https://github.com/TobiasWinchen/CRPropa3/tree/tf17_fix).
@tfitoussi , please create a new pull-request based on this branch, we can then start a proper review. From what I have seen so far, I guess there will be only minor changes needed.

**Comment by MRCWirtz** [comment]
@TobiasWinchen Thank you!

**Comment by tfitoussi** [comment]
Sorry for the mess up branch ! I didn't realize that my merge with the master branch wasn't correct. 
Whatever I made a new pull-request with the branch from @TobiasWinchen. 
Thank you !

**Pull request closed without merging**
