### PR TITLE
Diffusion using SDEs

### PR DESCRIPTION
**Pull request by lukasmerten**
This is the first version of a code using stochastic differential equations (SDEs) to describe the time evolution of a Fokker Planck transport equation. Here the integration of the transport equation is designed for the simulation of the Galactic transport problem. Hence, it could work as a low energy extension for the existing program.

### CODE REVIEW

**Comment by adundovi** [comment]
@lukasmerten is it possible that you add simple C++ tests for those additional component (cylinder source, boundary and breaking condition, observer)? I see that you added an integrated test in python, but maybe it will be easier to understand, to retractor if needed and to test the code if there are smaller test units that check only the basic functionality.

**Comment by lukasmerten** [comment]
I added now some simple tests for the new source, boundary and observer features. I followed the idea of the basic tests for other source or boundary modules. 
I plan to provide some jupyter notebooks with more detailed tests for the diffusion module, including explanatory notes and figures, in the next days.

**Comment by adundovi** [comment]
Great job. I'll review your commits, if nobody will be faster in doing this, and merge it with the main branch. If you want to add new packages in the continuous integration system, just edit file .travis.yml in the root directory of the project and there you can add scipy lib (just check what are the proper python2 and python3 package names in Ubuntu).

**Comment by DavidWalz** [comment]
Seems to be a SWIG related bug. However the test runs fine for me.

```
14/39 Testing: testDiffusionSDE
14/39 Test: testDiffusionSDE
Command: "/usr/bin/python3" "testDiffusionSDE.py"
Directory: /home/travis/build/CRPropa/CRPropa3/build
"testDiffusionSDE" start time: Jan 03 17:29 UTC
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "testDiffusionSDE.py", line 175, in <module>
    unittest.main()
  File "/usr/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib/python3.4/unittest/main.py", line 143, in createTests
    self.test = self.testLoader.loadTestsFromModule(self.module)
  File "/usr/lib/python3.4/unittest/loader.py", line 78, in loadTestsFromModule
    if isinstance(obj, type) and issubclass(obj, case.TestCase):
NameError: Unknown C global variable
<end of output>
Test time =   0.55 sec
----------------------------------------------------------
Test Failed.
"testDiffusionSDE" end time: Jan 03 17:29 UTC
"testDiffusionSDE" time elapsed: 00:00:00
----------------------------------------------------------
```

**Comment by DavidWalz** [comment]
pulled

**Pull request closed without merging**
