### PR TITLE
bugfix PhotoPionProduction resolving issue #225

### PR DESCRIPTION
**Pull request by Froehliche-Kernschmelze**
This pull request aims to resolve issue #225.

Changes occur in the `PhotoPionProduction.cpp` file in the treatment of secondary particles after SOPHIA has been called. In order to reduce the amount of extra run time needed, the code makes the following approach:

1) The outgoing particles from SOPHIA are being looped over as before, yet each proton and neutron (particle IDs 13 and 14) are not being added as secondaries directly. Their type (proton or neutron) and energy are being stored in two separate vectors `pnType` and `pnEnergy` and no secondary is being generated in this case, nor is the canditate's energy being modified. Particles that are not protons or neutrons are being treated as they were before.
2) The maximum energy of all outgoing protons and neutrons is searched in `pnEnergy` as this is the agreed criterion of being the primary particle after the process of photo pion production in #225 by @adundovi and me. This discrimination may obscure cases in which the primary achieves lower energies than its secondaries, yet the total energy and hadron numbers will always be preserved.
3) A loop over these remaining protons and neutrons either modifies the candidate's energy (if primary) or adds secondary nucleons (if not primary particles).

The advantage of this approach is that there is no brute-force 2nd loop over all outgoing particles but only over all nucleons emerging from the interaction. The second loop and the two extra vectors used for the type end energies of the nucleons could be avoided as well if SOPHIA would not return the 5-momentum of its secondaries but rather only a list of their energies. This modification is possible but being disregarded at this point as in a future work the particles' directional information may be invoked as well.

### CODE REVIEW

**Comment by adundovi** [comment]
@Froehliche-Kernschmelze since there is more than 1300 commits in your PR make a rebase locally and request PR again. We cannot merge this PR in the main repo otherwise.

**Comment by Froehliche-Kernschmelze** [comment]
Yeah that issue... did the Authors of #224 @TobiasWinchen or @antoniusf provide git commands for others to run on their systems? Because "rebase" is too abstract to be clear for anyone not familiar with the process.

In my case a simple `git rebase origin/master" causes as many conflicts as there are commits to be rebased.

**Comment by lukasmerten** [comment]
@Froehliche-Kernschmelze since also your origin/master has ~1300 diverged commits with CRPropa3/master I suggest to do the following:

1.) Update your master to be exactly equal to the CRPropa3/master. This could be done e.g. with `git reset --hard upstream/master`, when upstream is pointing to the CRPropa3 repo. Make sure to save local changes because they will be overwritten (see e.g. [here](https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files)).

2.) Checkout a new branch `git checkout -b <Fix225>`

3.) Add the all relevant files necessary for your pull request and create a commit

4.) Force push to the remote branch from which you created this pull request. (Make sure have a local copy before fore pushing. `git push -f <remote> <branch>`

I a ssume that a similar process has to be done for your other pull request and I am sorry for the extra work.

**Comment by lukasmerten** [comment]
On the physics side, I do agree with @Froehliche-Kernschmelze proposed way to add the secondaries correctly.

**Comment by Froehliche-Kernschmelze** [comment]
Thanks a lot @lukasmerten ! As far as I overlook the situation, this pull request is ready for review now.

**Comment by adundovi** [comment]
I've reviewed the changes. No additional comments. Great work! I'll merge it.

**Comment by lukasmerten** [comment]
@Froehliche-Kernschmelze Do you alreday have an idea how "relevant" this bug was? Can/Should we rerun some of the simulation of the CRPropa3 paper?

**Comment by Froehliche-Kernschmelze** [comment]
> @Froehliche-Kernschmelze Do you alreday have an idea how "relevant" this bug was? Can/Should we rerun some of the simulation of the CRPropa3 paper?

This bug was **only relevant to setups where the PhotoPionProduction produces anti-nucleons** (for a detailed description of it's effects and scope see https://github.com/CRPropa/CRPropa3/issues/225#issue-414083923). If anti-nucleons were being produced, the bug usually led to faulty energy assignments to candidates in the order of several orders of magnitude and always produced only one instead of multiple secondary protons or neutrons. Hence both the energy and number of secondary protons / neutrons were affected.
Reading the [CRPropa3 paper](https://arxiv.org/pdf/1603.07142.pdf) there is a setup of 1 to 1000 EeV primary hadrons (sect. 4.1) and at these energies it is very likely that anti-nucleons had been produced in the PhotoPionProduction - hence potentially involving the bug. Yet it is out of my judgment how results have been affected, yet to entirely be on the safe side I recommend re-evaluating all simulations that could involve this issue.

**Pull request merged**
